---
- hosts: all
  tasks: 
  - name: i want to ping 
    ping:

  - name: I want to install webserver
    apt:
      name: apache2
      state: present  

  - name: i want to install tree
    apt:
      name: tree
      state: present   
