---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - name: i want to ping 
      ping:
  
  
    - name: i want to install tree
      apt:
        name: tree
        state: present
      when: ansible_os_family == "Debian"

    - name: i want to start the tree
      apt:
        name: tree
        state: present
      when: ansible_os_family == "Debian" 

    - name: i want to install redhat
      dnf:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"   

    - name: i wnat to start redhat
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"    