---
- hosts: all
  tasks:
  - name: i want  to install webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debian"  

  - name: i want   to start webserver 
    service: 
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install redhat on server
    dnf:
      name: httpd
      state: present   
    when: ansible_os_family=="Redhat" 

  - name: i wnat to start redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family=="Redhat"
        