---
- hosts: all
  tasks:
  - name: i want  to install webserver
    apt: 
      name: apache2
      state: present
 
  - name: i want   to start webserver 
    service: 
      name: apache2
      state: started

  - name: i want to ping
    ping:   

  - name: i want to install git on ubuntu
    apt:
      name: git
      state: present  

        