---
- hosts: [mywebserver]
  tasks:
  - name: i want  to install webserver
    apt: 
      name: apache2
      state: present
    when: ansible_os_family=="Debian"  

  - name: i want   to start webserver 
    service: 
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: Install the latest version of Redhat
    ansible.builtin.dnf:
      name: httpd
      state: present
    when: ansible_os_family=="Redhat"

  - name:  i want to start the  Redhat
    ansible.builtin.dnf:
      name: httpd
      state: started
    when: ansible_os_family=="Redhat"  



